# Generated by Django 3.2.6 on 2021-08-20 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(blank=True, null=True)),
                ('paid', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dial_code', models.CharField(choices=[('+91', '+91 (India)')], default='+91', max_length=4)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(message='Only digits are allowed.', regex='^\\d*$')])),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('Ah', 'Ahmednagar'), ('Ak', 'Akola'), ('Am', 'Amravati'), ('Au', 'Aurangabad'), ('Be', 'Beed'), ('Bh', 'Bhandara'), ('Bu', 'Buldhana'), ('Ch', 'Chandrapur'), ('Dh', 'Dhule'), ('Ga', 'Gadchiroli'), ('Go', 'Gondia'), ('Hi', 'Hingoli'), ('Ja', 'Jalgaon'), ('Jan', 'Jalna'), ('Ko', 'Kolhapur'), ('La', 'Latur'), ('Mu', 'Mumbai'), ('Ng', 'Nagpur'), ('Na', 'Nanded'), ('Nab', 'Nandurbar'), ('Ns', 'Nashik'), ('Os', 'Osmanabad'), ('Pa', 'Parbhani'), ('Pu', 'Pune'), ('Ra', 'Raigad'), ('Rt', 'Ratnagiri'), ('Sa', 'Sangli'), ('St', 'Satara'), ('Si', 'Sindhudurg'), ('So', 'Solapur'), ('Th', 'Thane'), ('Wa', 'Washim'), ('Ya', 'Yavatmal')], default='Mu', max_length=3)),
                ('postal_code', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('C', 'Cash on Delivery ')], default='S', max_length=1)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
            options={
                'verbose_name': 'order details',
                'verbose_name_plural': 'order details',
            },
        ),
    ]
