# Generated by Django 3.2.6 on 2021-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210824_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('C', 'Cash on Delivery ')], default='S', max_length=1),
        ),
    ]
