# Generated by Django 3.2.6 on 2021-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orderdetails_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='label_colour',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('Su', 'success'), ('D', 'danger'), ('W', 'warning'), ('I', 'info')], default='P', max_length=9),
        ),
    ]
