# Generated by Django 3.2.6 on 2021-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210831_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
