# Generated by Django 3.2.6 on 2021-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210905_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
